In [2]:
#Load dependencies and define data files to import
from datetime import datetime as dt, timedelta
import pandas as pd
url2017='https://hfdapp.houstontx.gov/311/311-Public-Data-Extract-2017.txt'
url2018='https://hfdapp.houstontx.gov/311/311-Public-Data-Extract-2018.txt'
url2019='https://hfdapp.houstontx.gov/311/311-Public-Data-Extract-2019.txt'
url2020='https://hfdapp.houstontx.gov/311/311-Public-Data-Extract-monthly.txt'

In [3]:
#Create 2017 data frames
data2017=pd.read_csv(url2017,header=5,sep='|',error_bad_lines=False)

b'Skipping line 9979: expected 29 fields, saw 30\nSkipping line 16339: expected 29 fields, saw 30\n'
b'Skipping line 171264: expected 29 fields, saw 45\n'
b'Skipping line 210681: expected 29 fields, saw 30\n'
b'Skipping line 293912: expected 29 fields, saw 30\n'
b'Skipping line 327537: expected 29 fields, saw 30\n'

In [6]:
data2017=data2017.drop(data2017.index[0]).reset_index(drop=True)
data2017.columns=['case number','sr location','county','district','neighborhood','tax id','trash quad','recycle quad','trash day','heavy trash day','recycle day','key map',
                'management district','department','division','sr type','queue','sla','status','sr create date','due date','date closed','overdue','title','x','y','latitude',
                'longitude','channel type']
data2017[['sr create date','due date','date closed']]=data2017[['sr create date','due date','date closed']].apply(pd.to_datetime,errors='coerce')
top2017=data2017.groupby(['sr type'])['case number'].count().sort_values(ascending=False).head(20)
data2017.shape

(364276, 29)

In [5]:
data2017

,CASE NUMBER,SR LOCATION,COUNTY,DISTRICT,NEIGHBORHOOD,TAX ID,TRASH QUAD,RECYCLE QUAD,TRASH DAY,HEAVY TRASH DAY,...,SR CREATE DATE,DUE DATE,DATE CLOSED,OVERDUE,Title,x,y,LATITUDE,LONGITUDE,Channel Type
0,------------------------------,----------------------------------------------...,--------------------,----------,----------------------------------------,--------------------,--------------------,--------------------,--------------------,--------------------,...,--------------------,--------------------,--------------------,--------------------,----------------------------------------------...,--------------------,--------------------,--------------------,--------------------,------------
1,12091834-101002444724,"7237 RHOBELL, HOUSTON TX 77016 ...",HARRIS,B,EAST LITTLE YORK / HOMESTEAD,0825260000007,NE,NW,TUESDAY,2nd Tuesday,...,2017-01-01 00:01:48,2017-01-13 00:01:48,2017-01-01 11:20:02,-11.53,Fire Hydrant-101002444724 ...,3142093.87216000000,13877642.08478000000,29.85674295,-95.29694519,Voice In
2,12091835-101002444725,"7613 APPLETON, HOUSTON TX 77022 ...",HARRIS,H,NORTHSIDE/NORTHLINE,0710210010005,NE,NW,MONDAY,3rd Monday,...,2017-01-01 00:07:29,2017-01-13 00:07:29,2017-01-01 04:50:02,-11.80,Fire Hydrant-101002444725 ...,3119895.80632000000,13867379.46029000000,29.83044921,-95.36794687,Voice In
3,101002444726,Intersection 3900 S GESSNER RD&10000 WESTPARK ...,Harris County,F,MID WEST,NULL,,,,,...,2017-01-01 00:14:04,2017-01-02 00:14:04,2017-01-01 00:23:57,-0.99,Traffic Signal Maintenance-101002444726 ...,3066827.71298000000,13826351.51512000000,29.72209924,-95.53907768,Voice In
4,101002444727,"1411 BONNER, HOUSTON TX 77007 ...",HARRIS,C,WASHINGTON AVENUE COALITION / MEMORIAL P,0221020000009,NW,NW,MONDAY,1st Wednesday,...,2017-01-01 00:17:23,2017-01-08 00:17:23,2017-01-04 14:01:37,-3.43,Code Violation Report for Multi-Family Housing...,NULL,NULL,29.77385877,-95.40257152,WEB
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
364272,12202634-101002866093,"20811 FOX CLIFF, UNINCORPORATED TX 77338 ...",HARRIS,,,1253970010008,,,,,...,2017-12-31 23:02:14,2018-01-10 23:02:13,2017-12-31 23:20:03,-9.99,Water Leak-101002866093 ...,3133543.11170000000,13937515.22717000000,30.02204559,-95.31796178,Voice In
364273,101002866094,"8414 AMBLEWOOD, HOUSTON TX 77072 ...",HARRIS,F,ALIEF,1002890000002,SW,SW,MONDAY,1st Monday,...,2017-12-31 23:04:27,2018-01-24 23:04:27,2018-01-22 17:18:47,-2.24,Request a New Recycling Container ...,NULL,NULL,29.68568433,-95.58144224,Unknown
364274,101002866095,"8414 AMBLEWOOD, HOUSTON TX 77072 ...",HARRIS,F,ALIEF,1002890000002,SW,SW,MONDAY,1st Monday,...,2017-12-31 23:05:28,2018-01-10 23:05:28,2018-01-03 17:37:08,-7.23,Repair or Replace Damaged or Missing Container...,NULL,NULL,29.68568433,-95.58144224,Unknown
364275,Warning: Null value is eliminated by an aggreg...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
364276,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
weather_data = pd.read_excel("../Clean Data Files/Weather_KIAHstation_2017-2020.xls")
weather_data

In [3]:
#Create 2018 data frames
data2018=pd.read_csv(url2018,header=5,sep='|',error_bad_lines=False)
data2018=data2018.drop(data2018.index[0]).reset_index(drop=True)
data2018.columns=['case number','sr location','county','district','neighborhood','tax id','trash quad','recycle quad','trash day','heavy trash day','recycle day','key map',
                'management district','department','division','sr type','queue','sla','status','sr create date','due date','date closed','overdue','title','x','y','latitude',
                'longitude','channel type']
data2018[['sr create date','due date','date closed']]=data2018[['sr create date','due date','date closed']].apply(pd.to_datetime,errors='coerce')
top2018=data2018.groupby(['sr type'])['case number'].count().sort_values(ascending=False).head(20)
data2018.shape

b'Skipping line 124864: expected 29 fields, saw 30\n'
C:\Users\phili\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3058: DtypeWarning: Columns (22) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

(399953, 29)

In [4]:
#Create 2019 data frames
data2019=pd.read_csv(url2019,header=5,sep='|',error_bad_lines=False)
data2019=data2019.drop(data2019.index[0]).reset_index(drop=True)
data2019.columns=['case number','sr location','county','district','neighborhood','tax id','trash quad','recycle quad','trash day','heavy trash day','recycle day','key map',
                'management district','department','division','sr type','queue','sla','status','sr create date','due date','date closed','overdue','title','x','y','latitude',
                'longitude','channel type']
data2019[['sr create date','due date','date closed']]=data2019[['sr create date','due date','date closed']].apply(pd.to_datetime,errors='coerce')
top2019=data2019.groupby(['sr type'])['case number'].count().sort_values(ascending=False).head(20)
data2019.shape

b'Skipping line 86859: expected 29 fields, saw 31\n'
b'Skipping line 124913: expected 29 fields, saw 30\n'
b'Skipping line 144497: expected 29 fields, saw 30\n'
b'Skipping line 218652: expected 29 fields, saw 31\n'
b'Skipping line 349873: expected 29 fields, saw 30\n'

(395258, 29)

In [5]:
#Create 2020 data frames
data2020=pd.read_csv(url2020,header=5,sep='|',error_bad_lines=False)
data2020=data2020.drop(data2020.index[0]).reset_index(drop=True)
data2020.columns=['case number','sr location','county','district','neighborhood','tax id','trash quad','recycle quad','trash day','heavy trash day','recycle day','key map',
                'management district','department','division','sr type','queue','sla','status','sr create date','due date','date closed','overdue','title','x','y','latitude',
                'longitude','channel type']
data2020[['sr create date','due date','date closed']]=data2020[['sr create date','due date','date closed']].apply(pd.to_datetime,errors='coerce')
top2020=data2020.groupby(['sr type'])['case number'].count().sort_values(ascending=False).head(20)
data2020.shape

(21209, 29)

In [6]:
data311=data2017.append([data2018,data2019])
data311['year']=data311['sr create date'].dt.year
types311=data311.groupby(['sr type','year'])['case number'].count().unstack('year').reset_index()
types311.columns=['sr type','2017','2018','2019']
data311.shape

(1159875, 30)

In [7]:
top2017

sr type
Missed Garbage Pickup                       26950
Container Problem                           25151
Water Leak                                  23661
Sewer Wastewater                            22585
Nuisance On Property                        18806
Traffic Signal Maintenance                  17424
Street Hazard                               13147
Missed Recycling Pickup                     12167
Storm Debris Collection                     10802
Water Service                               10778
Traffic Signs                               10595
Drainage                                     9382
Parking Violation                            8806
Dead Animal Collection                       8380
Trash Dumping or Illegal Dumpsite            7563
Heavy Trash Violation                        7476
Unclassified 311 Web Request                 7244
Recycling Cart Repair or Replace             6892
Street Condition                             6832
Missed Heavy Trash Pickup                    6416
Name: case number, dtype: int64

In [ ]:
top2018

In [ ]:
top2019

In [ ]:
top2020

In [ ]:
types311

In [ ]:
types311.to_csv('../Clean Data Files/Houston 311 SR Types by Year.csv',index=False,header=True)